import { Currency } from "./constants";

export const currencies = [
  new Currency("ARS", "Argentine Peso", "Argentina"),
  new Currency("LYD", "Libyan Dinar", "Libya"),
  new Currency("SSP", "South Sudanese Pound", "South Sudan"),
  new Currency("SYP", "Syrian Pound", "Syria"),
  new Currency("VES", "Venezuelan Bolívar Soberano", "Venezuela"),
  new Currency("YER", "Yemeni Rial", "Yemen"),
  new Currency("ZWL", "Zimbabwean Dollar", "Zimbabwe"),
  new Currency("AED", "UAE Dirham", "United Arab Emirates"),
  new Currency("AFN", "Afghan Afghani", "Afghanistan"),
  new Currency("ALL", "Albanian Lek", "Albania"),
  new Currency("AMD", "Armenian Dram", "Armenia"),
  new Currency("ANG", "Netherlands Antillian Guilder", "Netherlands Antilles"),
  new Currency("AOA", "Angolan Kwanza", "Angola"),
  new Currency("AUD", "Australian Dollar", "Australia"),
  new Currency("AWG", "Aruban Florin", "Aruba"),
  new Currency("AZN", "Azerbaijani Manat", "Azerbaijan"),
  new Currency("BAM", "Bosnia and Herzegovina Mark", "Bosnia and Herzegovina"),
  new Currency("BBD", "Barbados Dollar", "Barbados"),
  new Currency("BDT", "Bangladeshi Taka", "Bangladesh"),
  new Currency("BGN", "Bulgarian Lev", "Bulgaria"),
  new Currency("BHD", "Bahraini Dinar", "Bahrain"),
  new Currency("BIF", "Burundian Franc", "Burundi"),
  new Currency("BMD", "Bermudian Dollar", "Bermuda"),
  new Currency("BND", "Brunei Dollar", "Brunei"),
  new Currency("BOB", "Bolivian Boliviano", "Bolivia"),
  new Currency("BRL", "Brazilian Real", "Brazil"),
  new Currency("BSD", "Bahamian Dollar", "Bahamas"),
  new Currency("BTN", "Bhutanese Ngultrum", "Bhutan"),
  new Currency("BWP", "Botswana Pula", "Botswana"),
  new Currency("BYN", "Belarusian Ruble", "Belarus"),
  new Currency("BZD", "Belize Dollar", "Belize"),
  new Currency("CAD", "Canadian Dollar", "Canada"),
  new Currency("CDF", "Congolese Franc", "Democratic Republic of the Congo"),
  new Currency("CHF", "Swiss Franc", "Switzerland"),
  new Currency("CLP", "Chilean Peso", "Chile"),
  new Currency("CNY", "Chinese Renminbi", "China"),
  new Currency("COP", "Colombian Peso", "Colombia"),
  new Currency("CRC", "Costa Rican Colon", "Costa Rica"),
  new Currency("CUP", "Cuban Peso", "Cuba"),
  new Currency("CVE", "Cape Verdean Escudo", "Cape Verde"),
  new Currency("CZK", "Czech Koruna", "Czech Republic"),
  new Currency("DJF", "Djiboutian Franc", "Djibouti"),
  new Currency("DKK", "Danish Krone", "Denmark"),
  new Currency("DOP", "Dominican Peso", "Dominican Republic"),
  new Currency("DZD", "Algerian Dinar", "Algeria"),
  new Currency("EGP", "Egyptian Pound", "Egypt"),
  new Currency("ERN", "Eritrean Nakfa", "Eritrea"),
  new Currency("ETB", "Ethiopian Birr", "Ethiopia"),
  new Currency("EUR", "Euro", "European Union"),
  new Currency("FJD", "Fiji Dollar", "Fiji"),
  new Currency("FKP", "Falkland Islands Pound", "Falkland Islands"),
  new Currency("FOK", "Faroese Króna", "Faroe Islands"),
  new Currency("GBP", "Pound Sterling", "United Kingdom"),
  new Currency("GEL", "Georgian Lari", "Georgia"),
  new Currency("GGP", "Guernsey Pound", "Guernsey"),
  new Currency("GHS", "Ghanaian Cedi", "Ghana"),
  new Currency("GIP", "Gibraltar Pound", "Gibraltar"),
  new Currency("GMD", "Gambian Dalasi", "The Gambia"),
  new Currency("GNF", "Guinean Franc", "Guinea"),
  new Currency("GTQ", "Guatemalan Quetzal", "Guatemala"),
  new Currency("GYD", "Guyanese Dollar", "Guyana"),
  new Currency("HKD", "Hong Kong Dollar", "Hong Kong"),
  new Currency("HNL", "Honduran Lempira", "Honduras"),
  new Currency("HRK", "Croatian Kuna", "Croatia"),
  new Currency("HTG", "Haitian Gourde", "Haiti"),
  new Currency("HUF", "Hungarian Forint", "Hungary"),
  new Currency("IDR", "Indonesian Rupiah", "Indonesia"),
  new Currency("ILS", "Israeli New Shekel", "Israel"),
  new Currency("IMP", "Manx Pound", "Isle of Man"),
  new Currency("INR", "Indian Rupee", "India"),
  new Currency("IQD", "Iraqi Dinar", "Iraq"),
  new Currency("IRR", "Iranian Rial", "Iran"),
  new Currency("ISK", "Icelandic Króna", "Iceland"),
  new Currency("JEP", "Jersey Pound", "Jersey"),
  new Currency("JMD", "Jamaican Dollar", "Jamaica"),
  new Currency("JOD", "Jordanian Dinar", "Jordan"),
  new Currency("JPY", "Japanese Yen", "Japan"),
  new Currency("KES", "Kenyan Shilling", "Kenya"),
  new Currency("KGS", "Kyrgyzstani Som", "Kyrgyzstan"),
  new Currency("KHR", "Cambodian Riel", "Cambodia"),
  new Currency("KID", "Kiribati Dollar", "Kiribati"),
  new Currency("KMF", "Comorian Franc", "Comoros"),
  new Currency("KRW", "South Korean Won", "South Korea"),
  new Currency("KWD", "Kuwaiti Dinar", "Kuwait"),
  new Currency("KYD", "Cayman Islands Dollar", "Cayman Islands"),
  new Currency("KZT", "Kazakhstani Tenge", "Kazakhstan"),
  new Currency("LAK", "Lao Kip", "Laos"),
  new Currency("LBP", "Lebanese Pound", "Lebanon"),
  new Currency("LKR", "Sri Lanka Rupee", "Sri Lanka"),
  new Currency("LRD", "Liberian Dollar", "Liberia"),
  new Currency("LSL", "Lesotho Loti", "Lesotho"),
  new Currency("MAD", "Moroccan Dirham", "Morocco"),
  new Currency("MDL", "Moldovan Leu", "Moldova"),
  new Currency("MGA", "Malagasy Ariary", "Madagascar"),
  new Currency("MKD", "Macedonian Denar", "North Macedonia"),
  new Currency("MMK", "Burmese Kyat", "Myanmar"),
  new Currency("MNT", "Mongolian Tögrög", "Mongolia"),
  new Currency("MOP", "Macanese Pataca", "Macau"),
  new Currency("MRU", "Mauritanian Ouguiya", "Mauritania"),
  new Currency("MUR", "Mauritian Rupee", "Mauritius"),
  new Currency("MVR", "Maldivian Rufiyaa", "Maldives"),
  new Currency("MWK", "Malawian Kwacha", "Malawi"),
  new Currency("MXN", "Mexican Peso", "Mexico"),
  new Currency("MYR", "Malaysian Ringgit", "Malaysia"),
  new Currency("MZN", "Mozambican Metical", "Mozambique"),
  new Currency("NAD", "Namibian Dollar", "Namibia"),
  new Currency("NGN", "Nigerian Naira", "Nigeria"),
  new Currency("NIO", "Nicaraguan Córdoba", "Nicaragua"),
  new Currency("NOK", "Norwegian Krone", "Norway"),
  new Currency("NPR", "Nepalese Rupee", "Nepal"),
  new Currency("NZD", "New Zealand Dollar", "New Zealand"),
  new Currency("OMR", "Omani Rial", "Oman"),
  new Currency("PAB", "Panamanian Balboa", "Panama"),
  new Currency("PEN", "Peruvian Sol", "Peru"),
  new Currency("PGK", "Papua New Guinean Kina", "Papua New Guinea"),
  new Currency("PHP", "Philippine Peso", "Philippines"),
  new Currency("PKR", "Pakistani Rupee", "Pakistan"),
  new Currency("PLN", "Polish Złoty", "Poland"),
  new Currency("PYG", "Paraguayan Guaraní", "Paraguay"),
  new Currency("QAR", "Qatari Riyal", "Qatar"),
  new Currency("RON", "Romanian Leu", "Romania"),
  new Currency("RSD", "Serbian Dinar", "Serbia"),
  new Currency("RUB", "Russian Ruble", "Russia"),
  new Currency("RWF", "Rwandan Franc", "Rwanda"),
  new Currency("SAR", "Saudi Riyal", "Saudi Arabia"),
  new Currency("SBD", "Solomon Islands Dollar", "Solomon Islands"),
  new Currency("SCR", "Seychellois Rupee", "Seychelles"),
  new Currency("SDG", "Sudanese Pound", "Sudan"),
  new Currency("SEK", "Swedish Krona", "Sweden"),
  new Currency("SGD", "Singapore Dollar", "Singapore"),
  new Currency("SHP", "Saint Helena Pound", "Saint Helena"),
  new Currency("SLE", "Sierra Leonean Leone", "Sierra Leone"),
  new Currency("SOS", "Somali Shilling", "Somalia"),
  new Currency("SRD", "Surinamese Dollar", "Suriname"),
  new Currency("STN", "São Tomé and Príncipe Dobra", "São Tomé and Príncipe"),
  new Currency("SZL", "Eswatini Lilangeni", "Eswatini"),
  new Currency("THB", "Thai Baht", "Thailand"),
  new Currency("TJS", "Tajikistani Somoni", "Tajikistan"),
  new Currency("TMT", "Turkmenistan Manat", "Turkmenistan"),
  new Currency("TND", "Tunisian Dinar", "Tunisia"),
  new Currency("TOP", "Tongan Paʻanga", "Tonga"),
  new Currency("TRY", "Turkish Lira", "Turkey"),
  new Currency("TTD", "Trinidad and Tobago Dollar", "Trinidad and Tobago"),
  new Currency("TVD", "Tuvaluan Dollar", "Tuvalu"),
  new Currency("TWD", "New Taiwan Dollar", "Taiwan"),
  new Currency("TZS", "Tanzanian Shilling", "Tanzania"),
  new Currency("UAH", "Ukrainian Hryvnia", "Ukraine"),
  new Currency("UGX", "Ugandan Shilling", "Uganda"),
  new Currency("USD", "United States Dollar", "United States"),
  new Currency("UYU", "Uruguayan Peso", "Uruguay"),
  new Currency("UZS", "Uzbekistani So'm", "Uzbekistan"),
  new Currency("VND", "Vietnamese Đồng", "Vietnam"),
  new Currency("VUV", "Vanuatu Vatu", "Vanuatu"),
  new Currency("WST", "Samoan Tālā", "Samoa"),
  new Currency("XAF", "Central African CFA Franc", "CEMAC"),
  new Currency(
    "XCD",
    "East Caribbean Dollar",
    "Organisation of Eastern Caribbean States",
  ),
  new Currency("XDR", "Special Drawing Rights", "International Monetary Fund"),
  new Currency("XOF", "West African CFA franc", "CFA"),
  new Currency("XPF", "CFP Franc", "Collectivités d'Outre-Mer"),
  new Currency("YER", "Yemeni Rial", "Yemen"),
  new Currency("ZAR", "South African Rand", "South Africa"),
  new Currency("ZMW", "Zambian Kwacha", "Zambia"),
  new Currency("ZWL", "Zimbabwean Dollar", "Zimbabwe"),
];
